### ISSUE TITLE
Remove unreachable websites

### ISSUE THREAD

**Issue by venkivijay** [doxsch/developer-portfolios#1]
Some of the websites are [unreachable](https://user-images.githubusercontent.com/30868354/93706375-3ba0dc80-fb43-11ea-941c-394da09649fe.jpg). It would be nice if those unreachable websites are removed.

**Comment by doxsch** [comment]
Hi @venkivijay 

Thanks for your feedback. Will hopefully be fixed soon. I have opened a PR here: https://github.com/emmabostian/developer-portfolios/pull/266

**Comment by venkivijay** [comment]
Hi @doxsch,
That's great. But what I meant was to remove the unreachable links programmatically. Because not every time one can manually add and remove links when it becomes unreachable. 
And also it's meaningless to have those broken links on the website until the PR gets resolved.

**Comment by doxsch** [comment]
Hi @venkivijay 
you're absolutely right. I also think it doesn't make much sense to show the broken links. 
I'll fix that soon. 
Thanks again for the feedback
